---
output:
  pdf_document: default
  html_document: default
---
---
title: "Assignment4_ClusterAnalysis"
output: html_document
date: '2022-03-18'
output:
  html_document: default
  pdf_document: default
  ---

```{r cluster}
rm(list=ls())

library(readr)
library(dplyr)
library(caret)
library(factoextra)
library(tidyverse)
library(cluster)

#read Pharmaceuticals.csv 

pharma_df <- read.csv('C:\\Users\\madhu\\Downloads\\Pharmaceuticals.csv')

colSums(is.na(pharma_df)) # verify null column sums

#Cluster analysis for pharma

#a. Use only the numerical variables (1 to 9) to cluster the 21 firms. Justify the various choices made in
#conducting the cluster analysis, such as weights for different variables, the specific clustering algorithm(s)

pharma_df_numeric <- pharma_df[,c(3:11)] #numerical from 3 to 11

#scale quantitative variables in DF by z-score because normalization is very important in cluster analysis

nor <- as.data.frame(scale(pharma_df_numeric))
distance <- get_dist(nor)
fviz_dist(distance) #visuvalize a distance matrix

# Estimating the  number of clusters
# Elbow Method on scaled data to determine the value of k

fviz_nbclust(nor, FUNcluster = kmeans, method = "wss") + labs(subtitle = "Elbow Method")

# Silhouette Method on scaled data to determine the number of clusters
fviz_nbclust(nor,FUNcluster = kmeans,method = "silhouette")+labs(subtitle="Silhouette Method")

## The plots reveal that 5 clusters are sufficient to capture the data variations

set.seed(64060)
k5 <- kmeans(nor, center = 5, nstart = 25) # where k = 5
k5$centers #centriods
fviz_cluster(k5, data = nor) #cluster plot viz

k5$size

#K-Means Cluster Analysis - Fit the data with 5 clusters

data_fit <- kmeans(nor, 5)
aggregate(nor, by = list(data_fit$cluster), FUN = mean)
norm <- as.data.frame(nor, data_fit$cluster)
norm

```

#(b)Interpret the clusters with respect to the numerical variables used in forming the clusters
```
cluster 1 - Row 8, 6, 12
cluster 2 - Row 2, 18
cluster 3 - Row 5, 9, 14, 20
cluster 4 - Row 3, 4, 7, 10, 16, 19, 21
cluster 5 - Row 11, 13, 15, 17

By the output of function::  aggregate(nor, by = list(data_fit$cluster), FUN = mean), we can observe the following:

cluster 1 has highest Market_Cap, highest ROE, highest ROA, lowest Leverage and lowest Beta
cluster 2 has lowest Beta, lowest PE_Ratio
cluster 3 has lowest Market_Cap, highest Beta, highest Leverage, highest Rev_Growth, lowest PE_ratio
cluster 4 has highest PE_Ratio, lowest ROE, lowest ROA, lowest Net_Profit_Margin
cluster 5 has highest Asset_Turnover, lowest Revenue growth, highest Net_Profit_Margin

```

```{r plot}
#cluster plot

clusplot(nor, data_fit$cluster, color = TRUE, shade =TRUE, labels = 2, lines = 0)

```

```
#(c)Is there a pattern in the clusters with respect to the numerical variables (10 to 12)? 

Moderate buy, hold, strong buy recommendations

Cluster 1 has highest ROE, highest ROA, highest Market_Cap but Rev_Growth is not indicated to moderate sell 

Cluster 2 has lowest Beta, lowest Asset_Turnover so hold Recommendation

Cluster 3 has highest Beta, highest Leverage, highest Rev_Growth is strong to buy Recommendation

Cluster 4 has highest PE_Ratio, lowest ROE, ROA, Net_Profit_Margin is to hold buy Recommendation

Cluster 5 has highest Asset_Turnover, highest Net_Profit_Margin, lowest revenue growth is risky but to buy Recommendation

Cluster 5 and Cluster 3 moderate to buy Recommendation
Cluster 1,4 is hold Recommendation

# (d)Provide an appropriate name for each cluster using any or all of the variables in the dataset.

  Cluster 1 - highest Market_Cap,highest Leverage,highest Rev_Growth, lowest Leverage and Beta cluster -  Risky but high revenue

  Cluster 2 - lowest Rev_Growth,lowest PE_Ratio cluster - on hold 
 
  Cluster 3 - lowest PE_Ratio,lowest_ROE,lowest ROA, highest Leverage, highest Rev_growth, lowest Net_Profit_Margin cluster - moderate buy recomendation
 
  Cluster 4 - highest PE_Ratio, lowest ROA,lowest Asset_Turnover, lowest Net_Profit_Margin cluster - - hold recommendation
 
  Cluster 5 - highest Asset_Turnover, Net_Profit_Margin, lowest Rev_Growth cluster - strong buy 


```


